version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db123
  app:
    image: my-node-app
    ports: 
      - 13000:1337